### ISSUE TITLE
Issue Mocking Delayed Message Exchange

### ISSUE THREAD

**Issue by kamaubrian** [fridujo/rabbitmq-mock#271]
I am using a delayed exchange and been trying to mock it. I am getting the following

`Caused by: java.lang.IllegalArgumentException: No exchange type x-delayed-message
	at com.github.fridujo.rabbitmq.mock.exchange.MockExchangeFactory.build(MockExchangeFactory.java:31)
	at com.github.fridujo.rabbitmq.mock.MockNode.exchangeDeclare(MockNode.java:58)
	at com.github.fridujo.rabbitmq.mock.MockChannel.exchangeDeclare(MockChannel.java:244)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.springframework.amqp.rabbit.connection.CachingConnectionFactory$CachedChannelInvocationHandler.invoke(CachingConnectionFactory.java:1184)
	at com.sun.proxy.$Proxy176.exchangeDeclare(Unknown Source)
	at org.springframework.amqp.rabbit.core.RabbitAdmin.declareExchanges(RabbitAdmin.java:688)
	at org.springframework.amqp.rabbit.core.RabbitAdmin.lambda$declareExchange$0(RabbitAdmin.java:222)
	at org.springframework.amqp.rabbit.core.RabbitTemplate.invokeAction(RabbitTemplate.java:2151)
	at org.springframework.amqp.rabbit.core.RabbitTemplate.doExecute(RabbitTemplate.java:2110)
	... 96 more`

Anyone got this before ?

**Comment by ledoyen** [comment]
Hi,
as a feature that is not built in RabbitMQ but comes from a [plugin](https://github.com/rabbitmq/rabbitmq-delayed-message-exchange), it is not available by default in the mock either.

You need to register such an exchange through the `Configuration`.
