### ISSUE TITLE
No started transaction using Spring

### ISSUE THREAD

**Issue by matheussl22** [fridujo/rabbitmq-mock#31]
I'am imput depedence on pom.xml and a created Bean to connectionFactory(), but I have stacktrace: No started transaction (make sure you called txSelect before txRollback.
I have problem just when going exec the second test with rabbitmq.

I'm using Spring and Junit.

Bean:
```
@Configuration
class RabbitmqConfig {

    @Bean
    ConnectionFactory connectionFactory() {
        return new CachingConnectionFactory(new MockConnectionFactory());
    }

}
```

Error validade:
```
public RollbackOk txRollback() {
        if (this.transaction == null) {
            throw new IllegalStateException("No started transaction (make sure you called txSelect before txRollback");
        } else {
            this.transaction = null;
            return new com.rabbitmq.client.impl.AMQImpl.Tx.RollbackOk();
        }
    }
```

any help?

**Comment by ledoyen** [comment]
The code you quoted emulates the behavior of RabbitMQ, that is, when you try to **commit** or **rollback** a transaction without initiating it.

You may have encountered a bug, but I will need more context elements to figure it out.
So stacktrace, sample code, sample test, etc. are welcome.

**Comment by matheussl22** [comment]
<java.lang.IllegalStateException: No started transaction (make sure you called txSelect before txCommit
	at com.github.fridujo.rabbitmq.mock.MockChannel.txCommit(MockChannel.java:535)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.amqp.rabbit.connection.CachingConnectionFactory$CachedChannelInvocationHandler.invoke(CachingConnectionFactory.java:981)
	at com.sun.proxy.$Proxy227.txCommit(Unknown Source)
	at org.springframework.amqp.rabbit.connection.RabbitResourceHolder.commitAll(RabbitResourceHolder.java:164)
	at org.springframework.amqp.rabbit.connection.ConnectionFactoryUtils$RabbitResourceSynchronization.afterCompletion(ConnectionFactoryUtils.java:311)
	at org.springframework.transaction.support.TransactionSynchronizationUtils.invokeAfterCompletion(TransactionSynchronizationUtils.java:171)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.invokeAfterCompletion(AbstractPlatformTransactionManager.java:992)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.triggerAfterCompletion(AbstractPlatformTransactionManager.java:967)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:788)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:714)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.commitTransactionAfterReturning(TransactionAspectSupport.java:532)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:304)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689)>
