### ISSUE TITLE
Channels can be committed only once.

### ISSUE THREAD

**Issue by janssk1** [fridujo/rabbitmq-mock#71]
I'm using mock rmq with transactions using spring. Spring is reusing channels, even across transactions but the mockchannel fail big time the second time a 'reused' channel is committed. See below. 

AFAIK, a channel can be commited multiple times, without requiring another txSelect
```
#[101219 23:21:50,734 | vm010124 | ERROR |http-nio-9090-exec-5|org.springframework.transaction.support.TransactionSynchronizationUtils | TransactionSynchronization.afterCompletion threw exception]#
java.lang.IllegalStateException: No started transaction (make sure you called txSelect before txCommit
	at com.github.fridujo.rabbitmq.mock.MockChannel.txCommit(MockChannel.java:521)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.amqp.rabbit.connection.CachingConnectionFactory$CachedChannelInvocationHandler.invoke(CachingConnectionFactory.java:1140)
	at com.sun.proxy.$Proxy86.txCommit(Unknown Source)
	at org.springframework.amqp.rabbit.connection.RabbitResourceHolder.commitAll(RabbitResourceHolder.java:171)
	at org.springframework.amqp.rabbit.connection.ConnectionFactoryUtils$RabbitResourceSynchronization.afterCompletion(ConnectionFactoryUtils.java:332)
	at org.springframework.transaction.support.TransactionSynchronizationUtils.invokeAfterCompletion(TransactionSynchronizationUtils.java:171)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.invokeAfterCompletion(AbstractPlatformTransactionManager.java:992)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.triggerAfterCompletion(AbstractPlatformTransactionManager.java:967)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:788)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:714)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.commitTransactionAfterReturning(TransactionAspectSupport.java:534)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:305)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688)
```

**Comment by ledoyen** [comment]
Hi,
Thank you for reporting this.
I am working on it and get back to you soon.

**Comment by ledoyen** [comment]
@janssk1 I just made a release (1.0.13) with the fix for this bug.
It should be available in Maven central within 2 hours.
Please let me know if it works for you.

**Comment by janssk1** [comment]
@ledoyen , the fix works. Thanks for the quick turnaround.
