### ISSUE TITLE
Deleting unexisting queue causes NPE

### ISSUE THREAD

**Issue by janssk1** [fridujo/rabbitmq-mock#73]
Whereas the method should be **idempotent**.
Stacktrace:
```
Caused by: java.lang.NullPointerException: null
	at com.github.fridujo.rabbitmq.mock.MockNode.queueDelete(MockNode.java:90)
	at com.github.fridujo.rabbitmq.mock.MockChannel.queueDelete(MockChannel.java:323)
	at com.github.fridujo.rabbitmq.mock.MockChannel.queueDelete(MockChannel.java:318)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.amqp.rabbit.connection.CachingConnectionFactory$CachedChannelInvocationHandler.invoke(CachingConnectionFactory.java:1140)
	at com.sun.proxy.$Proxy86.queueDelete(Unknown Source)
	at org.springframework.amqp.rabbit.core.RabbitAdmin.lambda$deleteQueue$3(RabbitAdmin.java:315)
	at org.springframework.amqp.rabbit.core.RabbitTemplate.invokeAction(RabbitTemplate.java:2135)
	at org.springframework.amqp.rabbit.core.RabbitTemplate.doExecute(RabbitTemplate.java:2094)
```

**Comment by ledoyen** [comment]
I pushed a fix.
It will be available in the snapshot repository (see [using the latest snapshot](https://github.com/fridujo/rabbitmq-mock#using-the-latest-snapshot)).

Let me know if this works for you.

**Comment by ledoyen** [comment]
Closed without feedback.
