### ISSUE TITLE
Add support for mandatory flag

### ISSUE THREAD

**Issue by janssk1** [fridujo/rabbitmq-mock#91]
Would be nice if mandatory flag is respected. Right now (1.0.14-SNAPSHOT) it is just ignored. 
When using the recently added direct-reply combined with 'mandatory' there is even an exception: 

```
[main] WARN com.nokia.impact.adaptation.model.Result - Unexpected exception
java.lang.UnsupportedOperationException
	at com.github.fridujo.rabbitmq.mock.MockChannel.addReturnListener(MockChannel.java:111)
	at com.rabbitmq.client.RpcClient.<init>(RpcClient.java:116)
	at com.nokia.impact.broker.RabbitMQWritableChannel.lambda$null$2(RabbitMQWritableChannel.java:133)
	at com.nokia.impact.broker.RabbitTemplate.execute(RabbitTemplate.java:55)
	at com.nokia.impact.broker.RabbitMQWritableChannel.lambda$call$3(RabbitMQWritableChannel.java:120)
	at com.nokia.impact.adaptation.model.Result.execute(Result.java:34)
	at com.nokia.impact.broker.RabbitMQWritableChannel.call(RabbitMQWritableChannel.java:118)
	at com.nokia.impact.broker.RmqControllerChannels.callAdapter(RmqControllerChannels.java:75)
	at com.nokia.impact.broker.RmqControllerChannelsTest.call(RmqControllerChannelsTest.java:110)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```

**Comment by ledoyen** [comment]
Support for `returnListeners` added in #93
